# Generated by Django 3.2.7 on 2021-10-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20211027_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tags',
            field=models.ManyToManyField(blank=True, default='', to='base.Tag'),
        ),
    ]
