# Generated by Django 3.2.7 on 2021-10-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_customuser_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='tags',
        ),
        migrations.AddField(
            model_name='customuser',
            name='favorite_places',
            field=models.ManyToManyField(blank=True, to='base.Place'),
        ),
    ]
